"""add status to users

Revision ID: 12a3fc14808e
Revises: cd2bfa5f2f01
Create Date: 2026-10-05 12:24:47.312445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12a3fc14808e'
down_revision: Union[str, Sequence[str], None] = 'cd2bfa5f2f01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "users",
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            server_default="Active"
        )
    )

    op.alter_column(
        "users",
        "status",
        server_default=None
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    # ### end Alembic commands ###
